
// Output definitions for Terraform

export const outputsConfigYaml = `# --- Outputs Configuration ---

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "eks_kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubeconfig
  sensitive   = true
}

output "rds_instance_address" {
  description = "The address of the RDS instance"
  value       = module.rds.db_instance_address
  sensitive   = true
}

output "connection_instructions" {
  description = "Instructions to connect to the cluster"
  value       = "Run: aws eks update-kubeconfig --name devonn-eks-\${var.environment} --region \${var.aws_region}"
}

# Example tfvars file structure (create these in environments/prod.tfvars, environments/staging.tfvars, etc)
# aws_region = "us-west-2"
# environment = "prod"
# vpc_cidr = "10.0.0.0/16"
# availability_zones = ["us-west-2a", "us-west-2b"]
# private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
# public_subnet_cidrs = ["10.0.101.0/24", "10.0.102.0/24"]
# node_desired_capacity = 2
# node_max_capacity = 4
# node_min_capacity = 1
# node_instance_types = ["t3.medium"]
# node_disk_size = 50
# db_instance_class = "db.t3.micro"
# db_allocated_storage = 20
# db_max_allocated_storage = 50
# db_password = "CHANGE_ME_IN_PROD"`;
