
name: Devonn.AI Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}
    steps:
      - uses: actions/checkout@v3
      
      # Build the extension for deployment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" != "" ]; then
            ENV="${{ github.event.inputs.environment }}"
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            ENV="production"
          else
            ENV="development"
          fi
          echo "ENVIRONMENT=$ENV" >> $GITHUB_ENV
          
          if [ "$ENV" == "development" ]; then
            echo "API_URL=http://localhost:8000" >> $GITHUB_ENV
          elif [ "$ENV" == "staging" ]; then 
            echo "API_URL=https://staging-api.devonn.ai" >> $GITHUB_ENV
          else
            echo "API_URL=https://api.devonn.ai" >> $GITHUB_ENV
          fi
      
      - name: Validate OpenAI API Key
        if: ${{ env.ENVIRONMENT == 'production' }}
        run: node scripts/validate-openai-key.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Build extension
        run: npm run build:${{ env.ENVIRONMENT }}
      
      - name: Package extension
        run: |
          cd dist
          zip -r ../devonn-ai-${{ env.ENVIRONMENT }}.zip *
      
      - name: Upload to Chrome Web Store
        if: ${{ github.event.inputs.environment == 'production' || github.ref == 'refs/heads/main' }}
        run: |
          node scripts/upload-to-chrome-webstore.js
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          ZIP_PATH: devonn-ai-${{ env.ENVIRONMENT }}.zip
          PUBLISH_EXTENSION: ${{ env.ENVIRONMENT == 'production' }}
      
      - name: Create GitHub Release
        if: ${{ github.event.inputs.environment == 'production' || github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          files: devonn-ai-${{ env.ENVIRONMENT }}.zip
          name: Release ${{ github.ref_name }}
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "✅ *Deployment Successful!*\nEnvironment: ${{ env.ENVIRONMENT }}\nBranch: ${{ github.ref_name }}\nTriggered by: ${{ github.actor }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "❌ *Deployment Failed!*\nEnvironment: ${{ env.ENVIRONMENT }}\nBranch: ${{ github.ref_name }}\nTriggered by: ${{ github.actor }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true

  smoke-test:
    name: Post-Deployment Smoke Test
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check deployed extension
        run: |
          # This would be a script to verify the extension is working in the store
          echo "Running post-deployment verification tests"
          # Add actual verification here
          echo "Extension published successfully!"
          
  notify:
    name: Notify Team
    needs: [deploy, smoke-test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Determine status
        id: status
        run: |
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            echo "deployment_status=successful" >> $GITHUB_OUTPUT
          else
            echo "deployment_status=failed" >> $GITHUB_OUTPUT
          fi
      
      - name: Send deployment notification
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Deployment ${{ steps.status.outputs.deployment_status }} for Devonn.AI ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'development') }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL || '' }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

